CREATE DATABASE SQLINJECTION;
USE SQLINJECTION;
CREATE TABLE BANKBALANCE(
USERNAME varchar(20),
PASS varchar(20),
BALANCE INT );

select * from BANKBALANCE;

insert into BANKBALANCE(USERNAME,PASS,BALANCE)values("PANI","PANI@123",45000)
,("SHEKAR","SHEKAR@123",68000);
