CREATE database XYZ;
use xyz;
CREATE table EMPLOYEE(
ID int PRIMARY KEY,
NAME VARCHAR(20) ,
SALARY int);
insert INTO EMPLOYEE(ID,NAME,SALARY) VALUES(1,"ADAM",25000),(2,"BOB",30000),(3,"CASEY",40000);
select * FROM EMPLOYEE;